package composeicons.scanner.plugin

import org.gradle.api.Project
import org.gradle.testfixtures.ProjectBuilder
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Integration tests for [GenerateIconKeepRulesTask] using ProjectBuilder.
 *
 * Verifies:
 * - Output file structure (comment header + sorted keep rules)
 * - Deduplication across duplicate references
 * - Idempotency (same input → same byte-level output)
 * - Graceful handling of missing or empty manifests
 */
class GenerateIconKeepRulesTaskTest {

    private fun createTestProject(): Pair<Project, File> {
        val projectDir = createTempDir(prefix = "keep-rules-test-")
        val project = ProjectBuilder.builder()
            .withProjectDir(projectDir)
            .build()
        return project to projectDir
    }

    private fun createTask(project: Project): GenerateIconKeepRulesTask {
        val task = project.tasks.create("generateIconKeepRules", GenerateIconKeepRulesTask::class.java)
        val kspDir = project.layout.buildDirectory.dir("generated/ksp/debug")
        task.kspManifestFiles.from(
            kspDir.map { dir ->
                if (dir.asFile.isDirectory) {
                    project.fileTree(dir).matching { it.include("**/icon-usage.json") }
                } else {
                    project.files()
                }
            }
        )
        task.outputFile.set(
            project.layout.buildDirectory.file("generated/composeicons/proguard/icon-allowlist.pro")
        )
        return task
    }

    private fun writeManifest(projectDir: File, icons: List<Triple<String, String, String>>) {
        val dir = projectDir.resolve("build/generated/ksp/debug")
        dir.mkdirs()
        val entries = icons.joinToString(",\n") { (source, style, name) ->
            """
            {
                "source": "$source",
                "style": "$style",
                "name": "$name",
                "file": "TestScreen.kt",
                "line": 10,
                "column": 8
            }
            """.trimIndent()
        }
        dir.resolve("icon-usage.json").writeText(
            """
            {
                "module": ":app",
                "generatedAt": "2026-05-08T00:00:00Z",
                "icons": [$entries]
            }
            """.trimIndent()
        )
    }

    private fun outputFile(projectDir: File): File =
        projectDir.resolve("build/generated/composeicons/proguard/icon-allowlist.pro")

    // --- T1-03 tests ---

    @Test
    fun `single icon produces single keep rule`() {
        val (project, projectDir) = createTestProject()
        try {
            writeManifest(projectDir, listOf(Triple("tabler", "Outline", "Home")))
            createTask(project).execute()

            val output = outputFile(projectDir)
            assertTrue(output.exists(), "output file should exist")
            val lines = output.readLines()
            assertTrue(lines.any { it.contains("-keep class composeicons.tabler.outline.HomeKt { *; }") })
        } finally {
            projectDir.deleteRecursively()
        }
    }

    @Test
    fun `output starts with auto-generated comment`() {
        val (project, projectDir) = createTestProject()
        try {
            writeManifest(projectDir, listOf(Triple("tabler", "Outline", "Home")))
            createTask(project).execute()

            val firstLine = outputFile(projectDir).readLines().first()
            assertTrue(firstLine.startsWith("#"), "first line must be a comment, was: $firstLine")
            assertTrue(
                firstLine.contains("Auto-generated by composeicons-scanner"),
                "first line must mark file as auto-generated"
            )
        } finally {
            projectDir.deleteRecursively()
        }
    }

    @Test
    fun `multiple references deduplicated and sorted`() {
        val (project, projectDir) = createTestProject()
        try {
            writeManifest(
                projectDir,
                listOf(
                    Triple("tabler", "Outline", "Home"),
                    Triple("tabler", "Outline", "Home"), // duplicate
                    Triple("phosphor", "Bold", "Heart"),
                    Triple("lucide", "Outline", "Activity"),
                )
            )
            createTask(project).execute()

            val keepLines = outputFile(projectDir).readLines()
                .filter { it.startsWith("-keep") }
            assertEquals(3, keepLines.size, "duplicates must be removed")
            // alphabetic order
            assertTrue(keepLines[0].contains("composeicons.lucide.outline.ActivityKt"))
            assertTrue(keepLines[1].contains("composeicons.phosphor.bold.HeartKt"))
            assertTrue(keepLines[2].contains("composeicons.tabler.outline.HomeKt"))
        } finally {
            projectDir.deleteRecursively()
        }
    }

    @Test
    fun `task is idempotent`() {
        val (project, projectDir) = createTestProject()
        try {
            writeManifest(
                projectDir,
                listOf(
                    Triple("tabler", "Outline", "Home"),
                    Triple("phosphor", "Bold", "Heart"),
                )
            )
            val task = createTask(project)

            task.execute()
            val firstRun = outputFile(projectDir).readBytes()

            task.execute()
            val secondRun = outputFile(projectDir).readBytes()

            assertTrue(firstRun.contentEquals(secondRun), "second run must produce identical output")
        } finally {
            projectDir.deleteRecursively()
        }
    }

    @Test
    fun `missing manifest writes empty file with comment`() {
        val (project, projectDir) = createTestProject()
        try {
            // No manifest written
            createTask(project).execute()

            val output = outputFile(projectDir)
            assertTrue(output.exists(), "file must be created even without manifest")
            val lines = output.readLines()
            assertTrue(lines.first().startsWith("#"))
            assertTrue(lines.none { it.startsWith("-keep") }, "no keep rules expected")
        } finally {
            projectDir.deleteRecursively()
        }
    }

    @Test
    fun `empty manifest writes only comment`() {
        val (project, projectDir) = createTestProject()
        try {
            val dir = projectDir.resolve("build/generated/ksp/debug")
            dir.mkdirs()
            dir.resolve("icon-usage.json").writeText(
                """
                {
                    "module": ":app",
                    "generatedAt": "2026-05-08T00:00:00Z",
                    "icons": []
                }
                """.trimIndent()
            )

            createTask(project).execute()

            val output = outputFile(projectDir)
            val keepLines = output.readLines().filter { it.startsWith("-keep") }
            assertTrue(keepLines.isEmpty())
        } finally {
            projectDir.deleteRecursively()
        }
    }

    @Test
    fun `output path is build slash generated slash composeicons slash proguard`() {
        val (project, projectDir) = createTestProject()
        try {
            writeManifest(projectDir, listOf(Triple("tabler", "Outline", "Home")))
            createTask(project).execute()

            val expected = projectDir.resolve("build/generated/composeicons/proguard/icon-allowlist.pro")
            assertTrue(expected.exists(), "expected path: ${expected.absolutePath}")
        } finally {
            projectDir.deleteRecursively()
        }
    }
}
