package composeicons.scanner.plugin

import kotlinx.serialization.json.Json
import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import java.io.File

/**
 * Gradle task that generates an R8/ProGuard keep allowlist from the
 * KSP-produced `icon-usage.json` manifest.
 *
 * Configuration-cache compatible: all paths are surfaced as Provider-backed
 * properties; `execute()` does not touch [org.gradle.api.Project].
 *
 * Output: `build/generated/composeicons/proguard/icon-allowlist.pro` by default.
 *
 * If no manifest is found (KSP didn't run, or the project has no icons), the
 * file is still created with only the auto-generated comment header — this
 * guarantees downstream R8 tasks always have a valid file to read.
 */
abstract class GenerateIconKeepRulesTask : DefaultTask() {

    /**
     * Candidate manifest files. A `ConfigurableFileCollection` (rather than
     * `@InputDirectory`) is used so missing inputs degrade gracefully — the
     * KSP output directory may not exist on first build or in non-KSP projects.
     */
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val kspManifestFiles: ConfigurableFileCollection

    /** Destination of the generated allowlist `.pro` file. */
    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    /**
     * Strategy controlling rule shape. Defaults to [KeepRuleStrategy.AGGRESSIVE]
     * for backward compatibility; users typically set [KeepRuleStrategy.NONE]
     * via `composeIconsScanner { keepRuleStrategy = … }` when they want R8 to
     * rely solely on default reachability analysis.
     */
    @get:Input
    abstract val keepRuleStrategy: Property<KeepRuleStrategy>

    @TaskAction
    fun execute() {
        val manifestFile = kspManifestFiles.files.firstOrNull { it.exists() && it.name == "icon-usage.json" }
        val strategy = keepRuleStrategy.getOrElse(KeepRuleStrategy.AGGRESSIVE)

        val rules: List<String> = if (manifestFile == null) {
            logger.lifecycle("composeicons-scanner: no icon-usage.json found — emitting empty allowlist.")
            emptyList()
        } else {
            val json = Json { ignoreUnknownKeys = true }
            val manifest = json.decodeFromString<IconUsageManifest>(manifestFile.readText())
            toR8KeepRules(manifest.icons, strategy)
        }

        val out = outputFile.get().asFile
        out.parentFile.mkdirs()
        out.writeText(buildString {
            append("# Auto-generated by composeicons-scanner — DO NOT EDIT.\n")
            append("# Source: ").append(manifestFile?.absolutePath ?: "<no manifest>").append('\n')
            append("# Strategy: ").append(strategy.name).append('\n')
            append("# Total rules: ").append(rules.size).append('\n')
            for (rule in rules) {
                append(rule).append('\n')
            }
        })

        logger.lifecycle("composeicons-scanner: ${rules.size} keep rules ($strategy) → ${out.absolutePath}")
    }

    companion object {
        /** Locate `icon-usage.json` under a KSP output directory, returning null if absent. */
        internal fun findManifestFile(kspDir: File): File? {
            if (!kspDir.isDirectory) return null
            val candidates = listOf(
                kspDir.resolve("icon-usage.json"),
                kspDir.resolve("resources/icon-usage.json"),
            )
            return candidates.firstOrNull { it.exists() }
                ?: kspDir.walkTopDown().firstOrNull { it.name == "icon-usage.json" }
        }
    }
}

